### ISSUE TITLE
Promise based: idle()

### ISSUE THREAD

**Issue by plehegar** [w3c/requestidlecallback#1]
From @balasanjay
[[
Should't this be Promise based? Then we can hope to one day write something like:

```
for (int i = 0; i < n; i++) {
  await idle();
  // do work.
}﻿
```

]]
https://plus.google.com/+IlyaGrigorik/posts/1Y4atT8ghZB

**Comment by rmcilroy** [comment]
A Promise-like API is an interesting suggestion, however there are difficulties in marrying the Promise-like fulfilled semantics (required for await or .then()) with a the fact that an idle callback might not completed all it's work in one go, instead needing to 'repost and return immediately' before it's deadline runs out. Would the promise be resolved when the idle callback returned, even although it hasn't finished it's work yet (and has scheduled more work in a future requestIdleCallback)? If this was the case then the fulfilled semantics for these idle promises is not particularly useful - it only represents that the callback happened, not that the work was completed - thus some other out-of-bound signaling mechanism between the caller and callbacks would probably be required, which reduces the usefulness of the promise API.

The only other alternative I see would be to pass an object to the callback which it would call .resolve() on when it had completed, however this seems clunky and would probably cause correctness issues  (e.g., forgetting to call .resolve() in a certain codepath in the callback and causing a deadlock in the rest of the app).

I think an ES6 API which would provide better utility for requestIdleCallback would be in-built support for the yield operator for generator functions. I've written up some thoughts at https://github.com/w3c/requestidlecallback/issues/2

**Comment by balasanjay** [comment]
@rmcilroy 

I was thinking that idle() would return a Promise that would be fulfilled with empty data (or maybe a high-res timestamp) when the next idle time slice begins.

This is entirely equivalent to the current API; you can build one out of the other. But I thought it would be slightly nicer for it to be await-able out of the box.

**Comment by domenic** [comment]
Yes, @rmcilroy's comment seems a bit confused. The promise's fulfillment is not supposed to represent the work being done by author code. It's supposed to simply represent the browser becoming ready to do idle work. Using promises fulfilled with undefined to represent such state transitions is a pretty common pattern. See http://www.w3.org/2001/tag/doc/promises-guide#one-time-events and the following section.

However, on the more general question of whether this is a good idea: I am not sure. It is unclear to me how all this would work and be plumbed into implementations. A promise-based design would necessarily mix in the idle callbacks with other promise callbacks for promises that were fulfilled during that event loop turn or similar. Whereas, a callback-based design (like requestIdleCallback(fn)) would run all the promise callbacks first, then run `fn`, since any re-entry into author code will run a microtask checkpoint (which runs promise callbacks). If the desire was specifically to integrate with some UA infrastructure for idleness, maybe the callback design makes more sense?

Along similar lines, the mental model is a bit unclear to me. `requestIdleCallback(fn)` matches the model of "store this action to call when idle," whereas `idle().then(fn)` matches the model of "I promise that at some point I will become idle; you may subscribe to an object that tells you when that is." These are largely isomorphic models, so maybe it doesn't matter.

**Comment by rmcilroy** [comment]
Ahh I see, I got the wrong end of the stick and thought you were proposing an idle() function which took a function argument and returned a promise which was fulfilled when that callbacks had run.  An idle() function which returns a promise which is fulfilled with an IdleDeadline object when an idle period occurs sounds more interesting.

As you say, these models are entirely equivalent and one could be built from the other. To clarify the suggestion in my head this suggestion, I just want to check that the following (very contrived) code snippets would be equivalent.

With requestIdleCallback:

``` javascript
function doWork2(deadline) {  
  // do more work
}

function doWork1(deadline) {
  while (moreWorkToDo()) {
    // do some work
    if (deadline.isExceeded()) {
      requestIdleCallback(doWork1);  // continue doWork1 when idle again.
      return;
    }
  }
  requestIdleCallback(doWork2);
}

requestIdleCallback(doWork1, 1000); // make sure to start work within 1 second
```

With promises:

``` javascript
// make sure to start work within 1 second
idle(1000).then(function doWork1(deadline) {
  while (moreWorkToDo()) {
    // do some work
    if (deadline.isExceeded()) {
      idle().then(doWork1);
      return;
    }
  }
  idle().then(function(deadline2) {
    // do more work
  }
}
```

I'm not completely familiar with the await proposal, but if I understand it correctly, the above could be transformed into the following with await:

``` javascript
async function doWork() {
  deadline = await idle(1000);   // make sure to start work within 1 second
  while (moreWorkToDo()) {
    // do some work
    if (deadline.isExceeded()) {
      deadline = await idle();
    }
  }
  deadline = await idle();
  // do more work
}

doWork();
```

The last example with await certainly reads much better to me.  Would it work with the current await proposal?  I need to have a think about some of the implementation issues @domenic brought up regarding microtask checkpoints and other callbacks in the event loop turn...

**Comment by domenic** [comment]
Yep, the last example fits with `await` perfectly.

One other problem. Cancelable promises don't exist yet, even though there's massive pent-up demand for them and we (myself and @jakearchibald) are working to get them out as soon as possible. But if you were to go this route, canceling an idle callback would probably be blocked until we figure those out :-/.

**Comment by igrigorik** [comment]
@domenic how would @rmcilroy's await example work with a cancelable promise? E.g I schedule doWork() to run during the next idle period, but then shortly thereafter realize I need to run it now and want to cancel and run immediately.

**Comment by rmcilroy** [comment]
Given that cancelable promises aren't specified yet (and would be necessary for requestIdleCallback), my feeling is that we should build this API as a lower-level callback API (as currently spec'ed). While the await-based promise API is nice, it requires await, which is a while out (ES7 at the earliest), and the promise API can be built from the callback API in Javascript once that's available (which would also be required for other APIs like setTimeout or requestAnimationFrame where await might work nicely too).

Thoughts?

**Comment by igrigorik** [comment]
Yep, agreed. +1 for staying with current callback API.

**Comment by domenic** [comment]
Sounds good.

**Comment by balasanjay** [comment]
Makes sense to me.
