### ISSUE TITLE
Enable use of generator functions with yield in requestIdleCallback

### ISSUE THREAD

**Issue by rmcilroy** [w3c/requestidlecallback#2]
ES6 generator functions enable a function to yield and be later re-entered with context saved across callings. RequestIdleCallbacks are expected to "repost and exit" once they are coming close to their deadline. It would be nice if instead, they could pass a generator function to the requestIdleCallback API and then just be able to sprinkle 'yield' calls throughout this callback.  This would enable transformation of the following code:

``` javascript
 function doIdle1(deadline) {
   // do work 1...
   if (deadline.isExceeded()) {
     requestIdle(doIdle2);
   } else {
     doIdle2(deadline);
   }
 }
 function doIdle2(deadline) {
    // do work 2
 }

could be transformed into the following:

 function* doIdle(deadline) {
   // do work 1...
   yield;
   // do work 2
 }
```

**Comment by igrigorik** [comment]
@jakearchibald @paullewis you explored this pattern a few weeks back.. what was the conclusion?

**Comment by jakearchibald** [comment]
I really liked the ergonomics of using a generator. It means the developer just yields as often as they can, then they don't have to care so much about the deadline.

**Comment by domenic** [comment]
This is a classic abuse of generators where async/await is more appropriate. If the desire is syntactic support for yielding to the event loop, #1 is the correct design. If the desire is to yield a sequence of values to some caller, then `yield` makes sense---but I doubt that is the case.

#1 is much better, since it actually matches the concept of async work being done. E.g., the `async function` containing the `await`s will then return a promise that is fulfilled when all the work is done.

**Comment by domenic** [comment]
The OP is also problematic in that it implies we would synchronously re-enter the function in some cases, which can be hazardous; if you can't predict whether re-entrance will occur synchronously or asynchronously, it is hard to write robust code.

**Comment by rmcilroy** [comment]
Closing this given #1 is preferred.
