### ISSUE TITLE
"the Window object's active document" makes no sense

### ISSUE THREAD

**Issue by bzbarsky** [w3c/requestidlecallback#25]
This spec talks about "the Window object's active document."  There is no such thing.  A browsing context has an active document.  A Window has some set of documents associated with it, with no way to pick out the really relevant one that I can see.  I thought I saw some spec trying to deal with this by talking about a Window's "most recent document" or something like that, but I don't recall which spec that was...

Need to coordinate with the HTML spec to define the right thing here.

**Comment by igrigorik** [comment]
@annevk @domenic what's the right concept for us to use here?

**Comment by domenic** [comment]
> In the definition of requestIdleCallback below, references to the Document object [dom] are to be taken to be references to the Window object's active document.

This should go away

> Each Document has: 
> ...
> Let document be the Window object's active document object.

Why not just associate these things with Windows, instead of Documents? Then you can use "this `Window` object's idle callback identifier" etc. That is what setTimeout does, for the [list of active timers](https://html.spec.whatwg.org/#list-of-active-timers).

---

If you do stick with Documents, I think you want "this Window object's newest Document object", similar to [how `window.document` is defined](https://html.spec.whatwg.org/#dom-document-2). That links to ["each Document in a browsing context is associated with a Window object"](https://html.spec.whatwg.org/#concept-document-window).

**Comment by igrigorik** [comment]
> Why not just associate these things with Windows, instead of Documents?

That would, indeed, simplify things. @rmcilroy any objections?

**Comment by rmcilroy** [comment]
Nope, no objections, that would indeed makes sense.

**Comment by igrigorik** [comment]
@domenic @rmcilroy first run at it: https://github.com/w3c/requestidlecallback/pull/38 - please take a look.
